openapi: 3.0.0
info:
  title: Public Content Discovery API
  version: 1.0.0
  description: API for discovering and browsing public tracks, projects, and artists

servers:
  - url: /api/v1
    description: API v1

paths:
  /public/tracks:
    get:
      summary: Get public tracks
      description: Returns paginated list of public tracks with filtering and sorting
      operationId: getPublicTracks
      parameters:
        - name: sort
          in: query
          schema:
            type: string
            enum: [recent, popular, trending, liked]
            default: recent
        - name: genre
          in: query
          schema:
            type: string
          description: Filter by genre
        - name: mood
          in: query
          schema:
            type: string
          description: Filter by mood
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: cursor
          in: query
          schema:
            type: string
          description: Cursor for pagination (alternative to offset)
      responses:
        '200':
          description: List of public tracks
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PublicTrack'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /public/featured:
    get:
      summary: Get featured tracks
      description: Returns curated/featured public tracks
      operationId: getFeaturedTracks
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            maximum: 50
      responses:
        '200':
          description: Featured tracks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicTrack'

  /public/projects:
    get:
      summary: Get public projects
      description: Returns paginated list of public music projects
      operationId: getPublicProjects
      parameters:
        - name: sort
          in: query
          schema:
            type: string
            enum: [recent, popular]
            default: recent
        - name: genre
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of public projects
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PublicProject'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /public/artists:
    get:
      summary: Get public artists/personas
      description: Returns paginated list of public AI artists/personas
      operationId: getPublicArtists
      parameters:
        - name: sort
          in: query
          schema:
            type: string
            enum: [recent, popular, alphabetical]
            default: recent
        - name: genre
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of public artists
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PublicArtist'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /public/tracks/{trackId}:
    get:
      summary: Get public track details
      description: Returns detailed information about a specific public track
      operationId: getPublicTrackDetails
      parameters:
        - name: trackId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Track details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicTrackDetails'
        '404':
          description: Track not found or not public
        '403':
          description: Track is not public

components:
  schemas:
    PublicTrack:
      type: object
      required:
        - id
        - title
        - audio_url
        - cover_url
        - duration_seconds
        - created_at
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        audio_url:
          type: string
          format: uri
        cover_url:
          type: string
          format: uri
        duration_seconds:
          type: integer
        genre:
          type: string
          nullable: true
        mood:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        # User info (limited for privacy)
        creator:
          type: object
          properties:
            id:
              type: string
              format: uuid
            username:
              type: string
            avatar_url:
              type: string
              nullable: true
        # Engagement metrics
        play_count:
          type: integer
        like_count:
          type: integer
        share_count:
          type: integer
        is_liked:
          type: boolean
          description: Whether current user liked this track
        # Computed
        version_count:
          type: integer
        stem_count:
          type: integer
        has_lyrics:
          type: boolean

    PublicTrackDetails:
      allOf:
        - $ref: '#/components/schemas/PublicTrack'
        - type: object
          properties:
            lyrics:
              type: string
              nullable: true
            description:
              type: string
              nullable: true
            tags:
              type: array
              items:
                type: string
            stems:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  url:
                    type: string
            analysis:
              type: object
              nullable: true
              properties:
                bpm:
                  type: integer
                key_signature:
                  type: string
                instruments:
                  type: array
                  items:
                    type: string
                mood:
                  type: string
            related_tracks:
              type: array
              items:
                $ref: '#/components/schemas/PublicTrack'

    PublicProject:
      type: object
      required:
        - id
        - title
        - created_at
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
          nullable: true
        cover_url:
          type: string
          format: uri
          nullable: true
        genre:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        creator:
          type: object
          properties:
            id:
              type: string
            username:
              type: string
        track_count:
          type: integer
        total_duration:
          type: integer
          description: Total duration in seconds
        play_count:
          type: integer

    PublicArtist:
      type: object
      required:
        - id
        - name
        - created_at
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        bio:
          type: string
          nullable: true
        avatar_url:
          type: string
          format: uri
          nullable: true
        style_description:
          type: string
          nullable: true
        genre_tags:
          type: array
          items:
            type: string
        mood_tags:
          type: array
          items:
            type: string
        is_ai_generated:
          type: boolean
        created_at:
          type: string
          format: date-time
        creator:
          type: object
          properties:
            id:
              type: string
            username:
              type: string
        track_count:
          type: integer
        follower_count:
          type: integer

    Pagination:
      type: object
      properties:
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        has_more:
          type: boolean
        cursor:
          type: string
          nullable: true
          description: Cursor for next page
