/**
 * Centralized Icon Exports
 * Phase 1.1: Bundle Size Optimization
 * 
 * IMPORTANT: Import icons from this file instead of 'lucide-react' directly.
 * This enables better tree-shaking and consistent icon usage across the app.
 * 
 * @example
 * ```tsx
 * // ❌ Bad - direct import prevents optimal tree-shaking
 * import { Heart, Play, Pause } from 'lucide-react';
 * 
 * // ✅ Good - centralized import
 * import { Heart, Play, Pause } from '@/lib/icons';
 * ```
 */

// Re-export LucideIcon type for component props
export type { LucideIcon, LucideProps } from 'lucide-react';

// ============================================
// Navigation & Layout Icons
// ============================================
export {
  Home,
  Search,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  MoreVertical,
  ExternalLink,
  Link,
  LogOut,
  Settings,
  User,
  Users,
  Grid3x3,
  List,
  Layers,
  LayoutGrid,
  Filter,
  SlidersHorizontal,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Expand,
} from 'lucide-react';

// ============================================
// Media & Audio Icons
// ============================================
export {
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Repeat,
  Repeat1,
  Shuffle,
  Music,
  Music2,
  Music3,
  Music4,
  Mic,
  Mic2,
  MicOff,
  Headphones,
  Radio,
  Disc,
  Disc2,
  Disc3,
  AudioLines,
  AudioWaveform,
  ListMusic,
  PlayCircle,
  PauseCircle,
  StopCircle,
  CirclePlay,
  CirclePause,
  CircleStop,
} from 'lucide-react';

// ============================================
// Action Icons
// ============================================
export {
  Plus,
  Minus,
  Check,
  Circle,
  Square,
  Trash,
  Trash2,
  Edit,
  Edit2,
  Edit3,
  Pencil,
  PenLine,
  Copy,
  Clipboard,
  ClipboardCopy,
  ClipboardCheck,
  Save,
  Download,
  Upload,
  Share,
  Share2,
  Send,
  Reply,
  Forward,
  Undo,
  Undo2,
  Redo,
  Redo2,
  RotateCw,
  RotateCcw,
  RefreshCw,
  RefreshCcw,
  Scissors,
  Crop,
  Move,
  GripVertical,
  GripHorizontal,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Pin,
  PinOff,
} from 'lucide-react';

// ============================================
// Status & Feedback Icons
// ============================================
export {
  Loader2,
  CheckCircle,
  CheckCircle2,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Bell,
  BellRing,
  BellOff,
  Clock,
  Timer,
  TimerOff,
  Calendar,
  CalendarDays,
  Star,
  StarOff,
  Heart,
  HeartOff,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Award,
  Trophy,
  Medal,
  Crown,
  Zap,
  ZapOff,
  Sparkles,
  Flame,
  TrendingUp,
  TrendingDown,
  Activity,
  BarChart,
  BarChart2,
  BarChart3,
  PieChart,
  LineChart,
} from 'lucide-react';

// ============================================
// Content & Data Icons
// ============================================
export {
  FileText,
  File,
  FileAudio,
  FileAudio2,
  FileMusic,
  FileImage,
  FileVideo,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  Archive,
  Package,
  Box,
  Database,
  HardDrive,
  Tag,
  Tags,
  Hash,
  AtSign,
  Bookmark,
  BookmarkPlus,
  Lightbulb,
  Palette,
  Wand,
  Wand2,
  Sparkle,
  Image,
  ImagePlus,
  ImageOff,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  Type,
  Text,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Quote,
  BookOpen,
  Book,
} from 'lucide-react';

// ============================================
// Social & Communication Icons
// ============================================
export {
  MessageSquare,
  MessageCircle,
  MessagesSquare,
  Mail,
  MailOpen,
  Inbox,
  Globe,
  Globe2,
  Link2,
  Unlink,
  UserPlus,
  UserMinus,
  UserX,
  UserCheck,
  UserCog,
  Users2,
  UsersRound,
  Contact,
  Contact2,
  PersonStanding,
} from 'lucide-react';

// ============================================
// Music Production / Studio Icons
// ============================================
export {
  Piano,
  Guitar,
  Drum,
  Keyboard,
  FileSliders,
  Sliders,
  SlidersVertical,
  Gauge,
  Waves,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Power,
  PowerOff,
  ToggleLeft,
  ToggleRight,
  Dot,
  Circle as CircleIcon,
  CircleDot,
  CircleDotDashed,
  Hash as HashIcon,
  Binary,
} from 'lucide-react';

// ============================================
// Utility / Misc Icons
// ============================================
export {
  Sun,
  Moon,
  Cloud,
  CloudOff,
  CloudUpload,
  CloudDownload,
  Wifi,
  WifiOff,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Tv,
  Tv2,
  Cast,
  QrCode,
  Fingerprint,
  Shield,
  ShieldCheck,
  ShieldOff,
  ShieldAlert,
  Key,
  KeyRound,
  Wallet,
  CreditCard,
  DollarSign,
  Euro,
  Coins,
  Gift,
  ShoppingCart,
  ShoppingBag,
  Store,
  Rocket,
  Terminal,
  Code,
  Code2,
  Braces,
  Brackets,
  CircuitBoard,
  Cpu,
  MemoryStick,
  Webhook,
} from 'lucide-react';

// ============================================
// Library / Collection Icons (for Library page)
// ============================================
export {
  Library,
  Album,
  ListPlus,
  ListMinus,
  ListOrdered,
  ListFilter,
  ListChecks,
  ListX,
  LayoutList,
  Rows3,
  Columns3,
  LayoutDashboard,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  SidebarClose,
  SidebarOpen,
  Sidebar,
  Split,
  Merge,
  GitBranch,
  GitFork,
  GitMerge,
  History,
  Clock3,
  Clock4,
  Clock8,
  Clock12,
  Hourglass,
  AlarmClock,
} from 'lucide-react';
