// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-public-tracks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var search_public_tracks_default = defineTool({
  name: "search_public_tracks",
  title: "Search public tracks",
  description: "Search MusicVerse AI's public track catalog by title, genre, or mood. Returns id, title, genre, mood, duration, play count, and audio/cover URLs.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Search text matched against title, genre, mood, and prompt."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const like = `%${query}%`;
    const { data, error } = await supabase.from("tracks").select(
      "id, title, computed_genre, mood, duration_seconds, play_count, likes_count, audio_url, cover_url, created_at"
    ).eq("is_public", true).eq("status", "completed").or(`title.ilike.${like},computed_genre.ilike.${like},mood.ilike.${like},prompt.ilike.${like}`).order("play_count", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tracks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-track.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_track_default = defineTool2({
  name: "get_track",
  title: "Get track details",
  description: "Fetch full details for a single public track including all A/B versions, lyrics, and audio URLs.",
  inputSchema: {
    track_id: z2.string().uuid().describe("UUID of the track.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ track_id }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("tracks").select("*, track_versions(*)").eq("id", track_id).eq("is_public", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Track not found or not public." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { track: data }
    };
  }
});

// src/lib/mcp/tools/list-my-tracks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_tracks_default = defineTool3({
  name: "list_my_tracks",
  title: "List my tracks",
  description: "List the signed-in user's own tracks (public and private) with title, status, genre, duration, and audio URL.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20).describe("Max results (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("tracks").select("id, title, status, computed_genre, mood, duration_seconds, is_public, audio_url, cover_url, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tracks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's MusicVerse AI profile: display name, username, avatar, bio, and public flag.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("profiles").select("id, user_id, username, display_name, avatar_url, bio, is_public, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-my-credits.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_credits_default = defineTool5({
  name: "get_my_credits",
  title: "Get my credit balance",
  description: "Get the signed-in user's current credit balance and gamification stats (level, XP, streak).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("user_credits").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { balance: 0 }, null, 2) }],
      structuredContent: { credits: data }
    };
  }
});

// src/lib/mcp/tools/list-my-playlists.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_my_playlists_default = defineTool6({
  name: "list_my_playlists",
  title: "List my playlists",
  description: "List the signed-in user's playlists with title, description, cover, and track count.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(20).describe("Max results (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("playlists").select("*").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { playlists: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/like-track.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var like_track_default = defineTool7({
  name: "like_track",
  title: "Like or unlike a track",
  description: "Toggle a like on a public track as the signed-in user. Returns the new like state.",
  inputSchema: {
    track_id: z5.string().uuid().describe("UUID of the track to like/unlike."),
    action: z5.enum(["like", "unlike"]).default("like").describe("Whether to add or remove the like.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, destructiveHint: false, openWorldHint: false },
  handler: async ({ track_id, action }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    if (action === "unlike") {
      const { error: error2 } = await supabase.from("track_likes").delete().eq("track_id", track_id).eq("user_id", ctx.getUserId());
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return {
        content: [{ type: "text", text: `Unliked track ${track_id}` }],
        structuredContent: { track_id, liked: false }
      };
    }
    const { error } = await supabase.from("track_likes").insert({ track_id, user_id: ctx.getUserId() });
    if (error && !error.message.toLowerCase().includes("duplicate")) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Liked track ${track_id}` }],
      structuredContent: { track_id, liked: true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ygmvthybdrqymfsqifmj";
var mcp_default = defineMcp({
  name: "musicverse-ai-mcp",
  title: "MusicVerse AI",
  version: "0.2.0",
  instructions: "Tools for MusicVerse AI \u2014 an AI music creation platform. Public: `search_public_tracks`, `get_track`. Authenticated (OAuth): `list_my_tracks`, `list_my_playlists`, `get_my_profile`, `get_my_credits`, `like_track`.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_public_tracks_default, get_track_default, list_my_tracks_default, get_my_profile_default, get_my_credits_default, list_my_playlists_default, like_track_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
