-- Add MIME types for music notation and transcription files to project-assets bucket
-- This migration adds support for files generated by klang.io transcription service

UPDATE storage.buckets 
SET 
  allowed_mime_types = ARRAY[
    -- Existing audio formats
    'audio/mpeg', 
    'audio/wav', 
    'audio/mp3', 
    'audio/ogg', 
    'audio/webm',
    -- MIDI files (klang.io transcription output)
    'audio/midi',
    'audio/x-midi',
    -- Existing image formats
    'image/jpeg', 
    'image/png', 
    'image/webp', 
    'image/gif',
    -- Existing video formats
    'video/mp4', 
    'video/webm',
    -- Music notation formats (klang.io transcription output)
    'application/vnd.recordare.musicxml+xml',  -- MusicXML (.mxml, .xml)
    'application/vnd.recordare.musicxml',       -- MusicXML alternative MIME type
    'text/xml',                                 -- XML fallback for MusicXML
    'application/xml',                          -- XML fallback for MusicXML
    -- PDF sheet music (klang.io transcription output)
    'application/pdf',
    -- JSON data (klang.io transcription output)
    'application/json',
    -- Guitar Pro and other binary formats (klang.io transcription output)
    'application/octet-stream'
  ]
WHERE id = 'project-assets';
